# Generated by Django 4.2.3 on 2023-07-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawForProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_product', models.IntegerField(default=1, verbose_name='Quantity Required for Production')),
                ('is_produced', models.BooleanField(default=False, verbose_name='Need Fabrication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product', verbose_name='Product')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='product.raw', verbose_name='Raw Material')),
                ('sub_raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_raws', to='product.raw', verbose_name='Sub Raw Material')),
            ],
            options={
                'verbose_name': 'Raw Material for Production',
                'verbose_name_plural': 'Raw Materials for Production',
                'db_table': 'Raw_Materials_for_Production',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parallel', models.BooleanField(default=False, verbose_name='Parallel Fabrication')),
                ('parallel_quantity', models.IntegerField(default=1, verbose_name='Quantity for Parallel Production')),
                ('production_duration', models.DurationField(verbose_name='Time Consumed for Production')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('RawForProduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RawForProduction', to='fabrication.rawforproduction', verbose_name='Raw For Production')),
            ],
            options={
                'verbose_name': 'Production Process',
                'verbose_name_plural': 'Production Processes',
                'db_table': 'Production_Processes',
                'ordering': ('-created_at',),
            },
        ),
    ]
