version: '3.8'
services:
  smartkits-app:
    container_name: Smartkits
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - smartkits-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 